---
substitutions:
  device_id: '0fe8ed'
  device_name: 'ESP8266 Server Closet'
  static_ip: '192.168.20.200'

esp8266:
  board: nodemcuv2

packages:
  base: !include ../packages/_esphome.yaml

  # Temp sensor
  dht22: !include
    file: ../packages/dht22.yaml
    vars:
      room: 'Server Closet'
      data_pin: D4
