---
substitutions:
  device_id: '7756f8'
  device_name: 'ESP8266 Living Room'
  static_ip: '192.168.20.204'

esp8266:
  board: nodemcuv2

packages:
  base: !include ../packages/_esphome.yaml

  # Temp sensor
  dht22: !include
    file: ../packages/dht22.yaml
    vars:
      room: 'Living Room'
      data_pin: D4
