---
substitutions:
  device_id: 'abd1b5'
  device_name: 'ESP8622 TV/audio controller'
  static_ip: '192.168.20.58'

esp8266:
  board: nodemcuv2

packages:
  base: !include ../packages/_esphome.yaml

  # Infrared device setup
  esp8266: !include
    file: ../packages/ir/esp8266.yaml
    vars:
      pin: D8

  # Audio splitter IR transmitter
  audio: !include
    file: ../packages/ir/audio.yaml

  # Speaker IR transmitter
  dm9: !include
    file: ../packages/ir/dm9.yaml
    vars:
      room: 'Living Room'

  # Light sensor
  temt6000: !include
    file: ../packages/temt6000.yaml
    vars:
      room: 'Living Room'
      data_pin: 10

  # Temp/humidity sensor
  htu21d: !include
    file: ../packages/htu21d.yaml
    vars:
      room: 'Living Room'
      i2c_data_pin: D6
      i2c_clock_pin: D7
