---
substitutions:
  device_id: 'd6101c'
  device_name: 'S3 Mini'
  static_ip: '192.168.20.205'
  room: 'Office'
  #ble_mac: A4:C1:38:12:4E:93  # Govee downstairs
  ble_mac: A4:C1:38:33:39:2E  # Govee upstairs

esp32:
  board: lolin_s3_mini
  variant: esp32s3
  framework:
    type: arduino
    version: latest
    platform_version: 6.9.0  # Required for lolin_s3_mini board


packages:
  base: !include ../packages/_esphome.yaml

  # LED strip for ESP32
  led: !include
    file: ../packages/ws2813_esp32.yaml
    vars:
      room: ${room}
      num_leds: 129
      data_pin: 16

  # Govee BLE
  govee: !include
    file: ../packages/ble/govee.yaml
    vars:
      room: ${room}
      ble_mac: ${ble_mac}

  # Light sensor
  light: !include
    file: ../packages/bh1750.yaml
    vars:
      i2c_data_pin: 11
      i2c_clock_pin: 10
      room: ${room}
