---
esphome:
  name: ${device_id}

wifi:
  ssid: eggs_iot
  password: !secret wifi_password
  fast_connect: true

  manual_ip:
    static_ip: ${static_ip}
    gateway: 192.168.20.1
    subnet: 255.255.255.0
    dns1: 192.168.1.198

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_id} Fallback Hotspot
    password: !secret wifi_fallback

# Start a recovery AP if wifi fails to connect
# https://esphome.io/components/captive_portal.html
captive_portal:

# Enable OTA updates via port 8266
# https://esphome.io/components/ota.html
ota:

# Enable basic logger
# https://esphome.io/components/logger.html
logger:

# Use NTP for local clock
# https://esphome.io/components/time.html
time:
  - platform: sntp
    servers:
      - 192.168.1.198
    timezone: Australia/Melbourne
    id: esptime

# Setup connection to MQTT broker
# https://esphome.io/components/mqtt.html
mqtt:
  broker: 192.168.1.198
  keepalive: 60s
  discovery: true

# Expose each device's esphome version
# https://esphome.io/components/text_sensor/version.html
text_sensor:
  - platform: version
    name: ESPHome Version ${device_id}
