---
# https://esphome.io/components/sensor/dht.html
sensor:
  - platform: dht
    pin: ${data_pin}
    model: DHT22_TYPE2
    temperature:
      name: "${room} Temperature"
      id: dht22_temp
    humidity:
      name: "${room} Humidity"
      id: dht22_hum
