---
# Pin configuration for a HTU21D i2c temp/humidity sensor
defaults:
  room: ${device_id}


# https://esphome.io/components/i2c.html
i2c:
  sda: ${i2c_data_pin}
  scl: ${i2c_clock_pin}

# https://esphome.io/components/sensor/htu21d.html
sensor:
  - platform: htu21d
    temperature:
      name: $room Temperature
      id: htu21d_temp
    humidity:
      name: $room Humidity
      id: htu21d_hum
