---
# Trigger/echo ultrasonic distance sensor
#
# https://esphome.io/components/sensor/ultrasonic.html
sensor:
  - platform: ultrasonic
    trigger_pin: $trigger_pin
    echo_pin: $echo_pin
    name: "${room} SR04 Distance"
    update_interval: 5s
