---
# Pin configuration for an analog TEMT6000 sensor

# https://esphome.io/cookbook/temt6000.html
sensor:
  - platform: adc
    pin: $data_pin
    name: "$room Illuminance"
    device_class: illuminance
    unit_of_measurement: lx
    attenuation: auto
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0;
